import ClientOnly from './components/ClientOnly'
import RegisterModal from './components/models/RegisterModal'
import Navbar from './components/navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import ToasterProvider from './providers/ToasterProviders'
import LoginModal from './components/models/LoginModal'
import getCurrentUser from './actions/getCurrentUser'
import RentModal from './components/models/RentModal'




export const metadata: Metadata = {
  title: 'Airbnb clone',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body>

        <ClientOnly>
          <ToasterProvider/>
          <LoginModal/> 
         <RegisterModal/>
         <RentModal/>
        <Navbar currentUser = {currentUser}/>
        </ClientOnly>

       
        
        {children}</body>
    </html>
  )
}
